### ISSUE TITLE
Wärmeleistung falsch geschrieben in Ergebnis-Text 

### ISSUE THREAD

**Issue by stefano2734** [patbiber/heat-pump-calculator#1]
Siehe „Wäremleistung“ in Ergebnissen. Buchstabendreher
Zeile 46 in calc1.php

und Wäremeleistungsrechner habe ich auch noch gesehen

**Comment by patbiber** [comment]
Danke vielmals! Ich habe die Fehler behoben und den Text generell überarbeitet.

**Comment by patbiber** [comment]
Danke vielmals! Ich habe die Fehler behoben und den Text generell überarbeitet.
